# Generated by Django 5.1.6 on 2025-04-06 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_increase_about_field_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='about',
            field=models.TextField(blank=True, max_length=300, null=True, verbose_name='О себе'),
        ),
    ]
