# Generated by Django 5.1.6 on 2025-04-05 21:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lessons',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('event_day', models.DateField(null=True)),
                ('lesson_time', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Table_1',
            fields=[
                ('id_name', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Table_2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Table_3',
            fields=[
                ('id_name', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Steps',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('step_name', models.CharField(max_length=128, null=True)),
                ('lesson_m2m', models.ManyToManyField(to='ormsql.lessons')),
            ],
        ),
        migrations.CreateModel(
            name='Table_4',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, null=True)),
                ('fk_field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ormsql.table_3')),
            ],
        ),
        migrations.AddField(
            model_name='lessons',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ormsql.users'),
        ),
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('m2m', models.ManyToManyField(to='ormsql.users')),
            ],
        ),
    ]
