# Generated by Django 5.1.6 on 2025-02-12 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128, null=True)),
                ('surname', models.CharField(max_length=128, null=True)),
                ('add_day', models.IntegerField(null=True)),
                ('age', models.IntegerField(null=True)),
                ('active', models.BooleanField(null=True)),
                ('class_type', models.IntegerField(null=True)),
            ],
        ),
    ]
