# Generated by Django 5.1.6 on 2025-02-16 18:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ormsql', '0002_table_1_table_2_alter_users_add_day'),
    ]

    operations = [
        migrations.CreateModel(
            name='Table_3',
            fields=[
                ('id_name', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Table_4',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, null=True)),
                ('fk_fild', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ormsql.table_3')),
            ],
        ),
    ]
