# Generated by Django 5.1.6 on 2025-02-16 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ormsql', '0003_table_3_table_4'),
    ]

    operations = [
        migrations.RenameField(
            model_name='table_4',
            old_name='fk_fild',
            new_name='fk_field',
        ),
    ]
