# Generated by Django 5.1.6 on 2025-02-17 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ormsql', '0004_rename_fk_fild_table_4_fk_field'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('m2m', models.ManyToManyField(to='ormsql.users')),
            ],
        ),
    ]
