# Generated by Django 5.1.6 on 2025-02-17 18:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ormsql', '0005_categories'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='active',
        ),
        migrations.RemoveField(
            model_name='users',
            name='add_day',
        ),
        migrations.RemoveField(
            model_name='users',
            name='age',
        ),
        migrations.RemoveField(
            model_name='users',
            name='class_type',
        ),
        migrations.RemoveField(
            model_name='users',
            name='surname',
        ),
        migrations.CreateModel(
            name='Lessons',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('event_day', models.DateField(null=True)),
                ('lesson_time', models.IntegerField(null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ormsql.users')),
            ],
        ),
        migrations.CreateModel(
            name='Steps',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('step_name', models.CharField(max_length=128, null=True)),
                ('lesson_m2m', models.ManyToManyField(to='ormsql.lessons')),
            ],
        ),
    ]
