# Generated by Django 5.1.6 on 2025-04-11 08:46

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='tags',
            field=models.JSONField(default=list, blank=True, help_text='Выберите теги статьи'),
        ),
    ]
