# Generated by Django 5.1.6 on 2025-04-11 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20250411_0846'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articles',
            name='tags',
        ),
        migrations.AddField(
            model_name='articles',
            name='tags',
            field=models.JSONField(default=list, blank=True),
        ),
    ]
