# Generated by Django 5.1.6 on 2025-03-26 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='likes_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
