# Generated by Django 5.1.6 on 2025-03-29 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0009_alter_like_article'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['created_date']},
        ),
    ]
